run:
  modules-download-mode: readonly
  timeout: 5m
  skip-files:
    - "benchmark_test.go"
  go: "1.18"
linters:
  enable:
    - gofmt
    - goimports
    - govet
    - goconst
    - gocritic
    - gocyclo
    - prealloc
    - unconvert
    - unparam
